hyperparameters:
  hidden_size: 128       # Number of neurons in the hidden layer
  learning_rate: 0.001  # Learning rate for the optimizer
  num_epochs: 1000       # Number of training epochs
  batch_size: 32        # Batch size for training
  num_layers: 2         # Number of hidden layers
  model: "LSTM"          # ANN or LSTM 
  sequence_length: 30